import {StyleSheet} from 'react-native';

const common = StyleSheet.create({
  header: {
    backgroundColor: 'rgba(255, 255, 255, 1.0)',
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    height: 151,
    width: '100%',
    flexDirection: 'row',
  },
  button1: {
    borderTopLeftRadius: 22,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    borderTopRightRadius: 0,
    height: 53,
    width: 166,
    position: 'absolute',
    zIndex: 3,
    left: 41,
    bottom: 25,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  button2: {
    borderBottomRightRadius: 27,
    borderTopRightRadius: 27,
    height: 53,
    width: 187,
    right: 41,
    bottom: 25,
    position: 'absolute',
    zIndex: 2,
    paddingLeft: 20,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: 'white',
    fontSize: 12,
    textTransform: 'uppercase',
    textAlign: 'center',
    fontFamily: 'Rubik-Medium',
  },
  buttonSelected: {
    backgroundColor: '#64CFD1',
  },
  buttonUnSelected: {
    backgroundColor: '#F5F5F5',
  },
  buttonTextSelected: {
    color: '#7A7A7A',
    fontSize: 12,
    textTransform: 'uppercase',
    textAlign: 'center',
    fontFamily: 'Rubik-Medium',
  },
  tab: {
    width: '100%',
    flexDirection: 'row',
    flex: 1,
    position: 'absolute',
    bottom: 0,
    alignItems: 'center',
  },
  backgroundTab: {
    backgroundColor: '#fff',
    width: '100%',
    height: 87,
    bottom: 0,
    position: 'absolute',
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    top: 10,
  },
  tabButtonCenter: {
    flex: 1,
    bottom: 40,
    alignItems: 'center',
  },
  walkMeter: {
    width: 211,
    height: 74,
    borderRadius: 15,
    backgroundColor: 'white',
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    zIndex: 100,
    top: '29%',
    left: '25%',
  },
  walkMeterColumn: {
    flex: 1,
  },
  walkText: {
    fontSize: 12,
    fontFamily: 'Rubik-Medium',
    color: '#7A838E',
    textAlign: 'center',
    textTransform: 'uppercase',
  },

  alertContainer: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    position: 'absolute',
  },
  alertBackground: {
    width: '100%',
    height: '100%',
    backgroundColor: '#333333',
    position: 'absolute',
  },
  alert: {
    backgroundColor: 'white',
    borderRadius: 10,
    alignItems: 'center',
    marginHorizontal: 40,
    paddingHorizontal: 28,
  },
  alertIconTop: {
    top: -37,
    width: 74,
    height: 74,
  },
  alertIconBottom: {
    bottom: -45,
    width: 90,
    height: 90,
  },
  alertTitle: {
    fontFamily: 'Rubik-Medium',
    fontSize: 18,
    color: '#7A838E',
    textAlign: 'center',
  },
  alertMessage: {
    fontFamily: 'Rubik-Light',
    fontSize: 14,
    color: '#7A838E',
    textAlign: 'center',
    marginTop: 20,
    lineHeight: 22,
  },
  alertUrl: {borderBottomWidth: 1, borderBottomColor: '#7A838E'},
  alertUrlText: {
    color: '#7A838E',
    fontFamily: 'Rubik-Medium',
    fontSize: 13,
    marginTop: 25,
  },
});
export default common;
