import {StyleSheet} from 'react-native';

const dashboard = StyleSheet.create({
  container: {
    backgroundColor: '#eee',
    width: '100%',
    height: '100%',
    flex: 1,
    flexDirection: 'column',
  },
  meter: {
    width: '100%',
    height: 246,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 45,
  },
  metersCircle: {
    position: 'absolute',
  },
  metersDashes: {
    position: 'absolute',
    tintColor: 'white',
  },
  metersReading: {
    position: 'absolute',
    backgroundColor: 'white',
    width: 170,
    height: 170,
    borderRadius: 85,
    flexDirection: 'column',
    justifyContent: 'center',
    paddingBottom: 20,
  },
  metersTitle: {
    fontSize: 55,
    color: '#64CFD1',
    textAlign: 'center',
    fontFamily: 'Rubik-Medium',
  },
  metersSubtitle: {
    fontSize: 11,
    color: 'black',
    textAlign: 'center',
    fontFamily: 'Rubik-Regular',
  },
  metersStatus: {
    position: 'absolute',
    width: 246,
    height: 246,
    // borderRadius: 180,
  },
  metersDot: {
    position: 'absolute',
    left: 105,
    top: 232,
    // borderRadius: 180,
  },
  readingsHeader: {
    color: '#57DBDE',
    fontSize: 18,
    textAlign: 'center',
    marginTop: 29,
    fontFamily: 'Rubik-Medium',
  },
  readings: {
    flexDirection: 'row',
    marginTop: 25,
  },
  flex1: {
    flex: 1,
  },
  readingsTitle: {
    color: 'black',
    fontSize: 24,
    textAlign: 'center',
    fontFamily: 'Rubik-Medium',
  },
  readingsSubTitle: {
    fontSize: 12,
    color: 'gray',
    textAlign: 'center',
    fontFamily: 'Rubik-Regular',
  },
  banners: {
    flexDirection: 'row',
    marginTop: 69,
    justifyContent: 'space-between',
  },
  leftBanner: {
    backgroundColor: 'white',
    borderTopRightRadius: 36,
    borderBottomRightRadius: 36,
    paddingHorizontal: 42,
    paddingVertical: 12,
  },
  leftBannerTitle: {
    color: 'black',
    fontSize: 14,
    textAlign: 'center',
    fontFamily: 'Rubik-Regular',
  },
  leftBannerSubTitle: {
    fontSize: 24,
    color: '#64CFD1',
    textAlign: 'center',
    fontFamily: 'Rubik-Medium',
  },
  rightBanner: {
    backgroundColor: '#64CFD1',
    borderTopLeftRadius: 36,
    borderBottomLeftRadius: 36,
    paddingHorizontal: 52,
    paddingVertical: 12,
  },
  rightBannerTitle: {
    color: 'white',
    fontSize: 14,
    textAlign: 'center',
    fontFamily: 'Rubik-Regular',
  },
  rightBannerSubTitle: {
    fontSize: 24,
    color: 'white',
    textAlign: 'center',
    fontFamily: 'Rubik-Medium',
  },
  toggle: {
    bottom: 120,
    left: 38,
    width: 70,
    height: 31,
    position: 'absolute',
  },
  toggleBackground: {
    width: 70,
    height: 31,
    backgroundColor: '#F4F4F4',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#CECECE',
    justifyContent: 'center',
  },
  toggleText: {
    fontSize: 14,
    fontFamily: 'Rubik-Medium',
    color: '#DDDDDD',
    textAlign: 'right',
    width: '100%',
    position: 'absolute',
    right: 10,
  },
  toggleCircle: {
    position: 'absolute',
    left: 4,
    width: 22,
    height: 22,
    backgroundColor: '#64CFD1',
    borderRadius: 16,
    shadowColor: 'rgba(0,0,0, 1)',
    shadowOffset: {width: 0, height: 3},
    shadowRadius: 6,
    shadowOpacity: 0.16,
  },
});
export default dashboard;
